[zh-tw]
  title                = "ALFA Network 無線網卡台灣代理 | 榆閤科技 Yopitek"
  locale               = "zh-TW"
  label               = "繁體中文"
  weight               = 1
  contentDir           = "content/zh-tw"
  [zh-tw.params]
    dateFormat         = "2006年1月2日"
    displayName        = "🇹🇼 繁體中文"

[zh-cn]
  title                = "ALFA Network 无线网卡台湾代理 | 榆阖科技 Yopitek"
  locale               = "zh-CN"
  label               = "简体中文"
  weight               = 2
  contentDir           = "content/zh-cn"
  [zh-cn.params]
    displayName        = "🇨🇳 简体中文"

[en]
  title                = "ALFA Network Authorized Distributor Taiwan | Yopitek Ltd"
  locale               = "en"
  label               = "English"
  weight               = 3
  contentDir           = "content/en"
  [en.params]
    displayName        = "🇬🇧 English"

[ja]
  title                = "ALFA Network 無線LAN正規販売代理店 台湾 | Yopitek"
  locale               = "ja"
  label               = "日本語"
  weight               = 4
  contentDir           = "content/ja"
  [ja.params]
    displayName        = "🇯🇵 日本語"

[ar]
  title                = "موزع ALFA Network المعتمد في تايوان | Yopitek"
  locale               = "ar"
  label               = "العربية"
  weight               = 5
  contentDir           = "content/ar"
  [ar.params]
    rtl                = true
    languageDirection  = "rtl"
    displayName        = "🇸🇦 العربية"

[es]
  title                = "Distribuidor Autorizado ALFA Network Taiwan | Yopitek Ltd"
  locale               = "es"
  label               = "Español"
  weight               = 6
  contentDir           = "content/es"
  [es.params]
    displayName        = "🇪🇸 Español"

[pt]
  title                = "Distribuidor Autorizado ALFA Network Taiwan | Yopitek Ltd"
  locale               = "pt"
  label               = "Português"
  weight               = 7
  contentDir           = "content/pt"
  [pt.params]
    displayName        = "🇧🇷 Português"

[ru]
  title                = "Авторизованный дистрибьютор ALFA Network Тайвань | Yopitek"
  locale               = "ru"
  label               = "Русский"
  weight               = 8
  contentDir           = "content/ru"
  [ru.params]
    displayName        = "🇷🇺 Русский"

[de]
  title                = "ALFA Network Autorisierter Distributor Taiwan | Yopitek Ltd"
  locale               = "de"
  label               = "Deutsch"
  weight               = 9
  contentDir           = "content/de"
  [de.params]
    displayName        = "🇩🇪 Deutsch"

[fr]
  title                = "Distributeur Agréé ALFA Network Taiwan | Yopitek Ltd"
  locale               = "fr"
  label               = "Français"
  weight               = 10
  contentDir           = "content/fr"
  [fr.params]
    displayName        = "🇫🇷 Français"
