[[main]]
  name       = "Solutions"
  pageRef    = "/solution"
  weight     = 10

[[main]]
  name       = "Products"
  weight     = 20
  [main.params]
    icon     = "tag"

  [[main]]
    name     = "ACS"
    pageRef  = "/products/acr"
    parent   = "Products"
    weight   = 21

  [[main]]
    name     = "ALFA Network"
    pageRef  = "/products/alfa"
    parent   = "Products"
    weight   = 22

  [[main]]
    name     = "Flipper Zero"
    pageRef  = "/products/flipperzero"
    parent   = "Products"
    weight   = 23

  [[main]]
    name     = "Graphic Cards"
    pageRef  = "/products/graphiccard"
    parent   = "Products"
    weight   = 24

  [[main]]
    name     = "HAK5"
    pageRef  = "/products/hak5"
    parent   = "Products"
    weight   = 25

  [[main]]
    name     = "iBeacon"
    pageRef  = "/products/ibeacon"
    parent   = "Products"
    weight   = 26

  [[main]]
    name     = "Mellanox"
    pageRef  = "/products/mellanox"
    parent   = "Products"
    weight   = 27

  [[main]]
    name     = "SDRLAB"
    pageRef  = "/products/sdrlab"
    parent   = "Products"
    weight   = 28


  [[main]]
    name     = "Sierra Wireless"
    pageRef  = "/products/sierra"
    parent   = "Products"
    weight   = 28

  [[main]]
    name     = "Ubiquiti"
    pageRef  = "/products/ubiquiti"
    parent   = "Products"
    weight   = 29

[[main]]
  name   = "Blog"
  pageRef = "/blog"
  weight  = 35

[[main]]
  name       = "Support"
  pageRef    = "/support"
  weight     = 30

[[main]]
  name       = "Contact"
  pageRef    = "/contact"
  weight     = 40
